export enum ApiTests {
  SWAP_ARB_TO_OP,
  SWAP_OP_SEPOLIA_TO_RARI_TESTNET,
  SWAP_ARB_SEPOLIA_TO_RARI_TESTNET,
  SWAP_RARI_TESTNET_TO_ARB_SEPOLIA,
  SWAP_ARB_TO_RARI,
  SWAP_RARI_TO_ARB,
  MULTI_HOP_OP_ARB_RARI,
}
